name: app5
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.6.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  scoped_model: ^2.0.0
  rxdart: ^0.27.7
  http: ^0.13.6
  json_annotation: ^4.9.0
  flutter_html: ^3.0.0
  cached_network_image: ^3.2.3
  shared_preferences: ^2.5.2
  country_code_picker: ^3.2.0
  url_launcher: ^6.3.1
  timeago: ^3.3.0
  flutter_rating_bar: ^4.0.1
  webview_flutter: ^4.10.0 
  font_awesome_flutter: ^10.8.0
  share_plus: ^10.1.4 
  place_picker: ^0.10.0
  location: ^8.0.0
  fluttertoast: ^8.2.12
  #flutter_paystack: ^1.0.7  // namespace migrant error
  #flutter_paystack_payment: ^0.1.3
  sign_in_with_apple: ^7.0.1
  image_picker: ^1.1.2
  #flutter_webview_plugin: ^0.4.0
  flutter_font_icons: ^2.2.7
  firebase_auth: ^5.5.1
  google_sign_in: ^6.3.0
  google_fonts: ^4.0.4 
  #flutter_stripe: ^11.4.0  // not required
  network_to_file_image: ^7.0.0
  firebase_core: ^3.12.1
  #firebase_analytics: ^11.4.4  // not required
  firebase_storage: ^12.4.4
  cloud_firestore: ^5.6.5
  photo_view: ^0.15.0
  intro_slider: ^4.2.1
  onesignal_flutter: ^5.3.0
  firebase_messaging: ^15.2.4
  rounded_loading_button: ^2.1.0
  pin_code_fields: ^8.0.1
  gradient_borders: ^1.0.1
  lottie: ^3.0.0
  #webview_cookie_manager: ^2.0.6
  flutter_localization: ^0.3.1
  intl: ^0.19.0
  path: ^1.9.0
  html: ^0.15.5
  path_provider: ^2.1.5
  crypto: ^3.0.6
  google_maps_flutter: ^2.12.1
  fab_circular_menu: ^1.0.2
  carousel_slider: ^5.0.0
  flutter_swiper_null_safety: ^1.0.2
  webview_cookie_manager: ^2.0.6
  




dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.2.19
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter_native_splash:
  image: lib/assets/images/splash.jpg
  color: "ffffff"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/images/icon.png"

flutter:

  uses-material-design: true

  assets:
    - lib/assets/images/
    - lib/assets/images/intro/

  fonts:
    - family: MStoreIcons
      fonts:
        - asset: lib/assets/fonts/Icons/MStoreIcons.ttf
    - family: Lexend_Deca
      fonts:
        - asset: lib/assets/fonts/Lexend_Deca/Lexend_Deca-Regular.ttf